# Kafka Configuration
kafka.bootstrap-servers=localhost:9092
kafka.topic.hubs=telemetry.hubs.v1
kafka.topic.sensors=telemetry.sensors.v1
# Kafka Producer Configuration
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
kafka.producer.acks=all
kafka.producer.retries=3
kafka.producer.request-timeout-ms=30000
kafka.producer.delivery-timeout-ms=60000