server.port=8081
grpc.client.echo.address=static://127.0.0.1:9090
grpc.client.echo.enableKeepAlive=true
grpc.client.echo.keepAliveWithoutCalls=true
grpc.client.echo.negotiationType=plaintext
spring.application.name=grpc-client